# Generated by Django 5.0 on 2023-12-30 21:27

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("information", models.CharField(max_length=50)),
                ("name", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254)),
                ("telephone", models.CharField(max_length=13)),
                ("compagny_name", models.CharField(max_length=50)),
                ("last_update", models.DateField()),
                ("creation_date", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="Contract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_amount", models.FloatField()),
                ("remaining_amount", models.FloatField()),
                (
                    "status",
                    models.CharField(
                        choices=[("Sign", "Sign"), ("To-sign", "To Sign")],
                        max_length=10,
                    ),
                ),
                ("creation_date", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("date_start", models.DateTimeField()),
                ("date_end", models.DateTimeField()),
            ],
        ),
    ]
